services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=user_image_db
    networks:
      - app-network

  user-image-service:
    build: .
    container_name: user-image-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/user_image_db
      - GCS_BUCKET_NAME=user-images-bucket
      - API_KEYS=test-key-1,test-key-2
      - ROOT_API_KEY=admin-root-key
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/gcp-credentials.json
    volumes:
      - ./credentials:/app/credentials
      - ./logs:/app/logs
    networks:
      - app-network

volumes:
  mongodb_data:
    name: mongodb_data

networks:
  app-network:
    driver: bridge